# Generated by Django 4.1.2 on 2022-12-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VCapp', '0002_invoice_alter_orders_options_alter_letter_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Letter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='VCapp.letter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
