# Generated by Django 4.1.2 on 2022-12-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VCapp', '0003_remove_invoice_order_invoice_letter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='VCapp.orders'),
        ),
    ]
