# Generated by Django 4.1.2 on 2022-12-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VCapp', '0005_rename_letter_invoice_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Order',
        ),
    ]
